name: inkmaster

services:
  db:
    image: miguela12485/db:1.0.0
    restart: always
    environment:
      MYSQL_DATABASE: inkmaster
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - red


  backend:
    image: laravel:1.0.0
    restart: always
    environment:
      DB_HOST: db
      DB_DATABASE: inkmaster
      DB_USERNAME: root
      DB_PASSWORD: rootpassword
    ports:
      - "8000:8000"
    networks:
      - red    

  frontend:
    image: angular:1.0.0
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - red

volumes:
  mysql_data:
  

networks:
  red:
    driver: bridge