version: '3.8'

services:
  # Laravel (PHP-FPM)
  laravel:
    build:
      context: ./backend               # Ruta al Dockerfile
      dockerfile: Dockerfile           # Opcional si se llama así
    container_name: laravel
    volumes:
      - ./backend-laravel:/var/www     # Sincroniza tu código con el contenedor
    ports:
      - "9000:9000"                     # Puerto PHP-FPM
    depends_on:
      - mysql
    networks:
      - appnet
    restart: unless-stopped

  # Base de datos MySQL
  mysql:
    image: mysql:latest
    container_name: mysql
    stdin_open: true
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    ports:
      - "3306:3306"
    restart: always
    networks:
      - appnet

  # Panel de administración phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: 123456789
    depends_on:
      - mysql
    networks:
      - appnet

  # Frontend Angular
  angular:
    build:
      context: ./frontend
    container_name: angular
    ports:
      - "4200:80"
    depends_on:
      - laravel
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:

volumes:
  db_data:
